In [1]:
import pandas as pd

In [2]:
info = {
    "Name": ["ROiht","Akash","Aditya"],
    "cgpa": [7.7,8.0,8.5]
}

df = pd.DataFrame(info)
print(df)
df

     Name  cgpa
0   ROiht   7.7
1   Akash   8.0
2  Aditya   8.5

     Name  cgpa
0   ROiht   7.7
1   Akash   8.0
2  Aditya   8.5

In [3]:
s = pd.Series([1,2,3,4,5,6])

print(s)
print(type(s))

#index
print(s[2])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>
3

In [4]:
s = pd.Series([1,2,3,4,5,6] , index = ["adam","bob","harsh", "jack","will","wick"])
print(s)

adam     1
bob      2
harsh    3
jack     4
will     5
wick     6
dtype: int64

In [5]:
s = pd.Series([1,2,3,4,5,"wick"] , index = ["adam","bob","harsh", "jack","will",25])
print(s)
print(s.index)
print(s["adam"])

adam        1
bob         2
harsh       3
jack        4
will        5
25       wick
dtype: object
Index(['adam', 'bob', 'harsh', 'jack', 'will', 25], dtype='object')
1

In [6]:
s1 = pd.Series([1,2,3,4,5,6])
s2 = pd.Series([10,20,30,40,50,60])
print(s1+s2)
s1[0] = 100
change_s1 = s1.drop(0)
print(s1)
print(change_s1)

0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64
0    100
1      2
2      3
3      4
4      5
5      6
dtype: int64
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [7]:
df = pd.DataFrame([["Rohit",23],["JAck",25],["Eve",27]], columns = ["Name","Age"])
print(df)

    Name  Age
0  Rohit   23
1   JAck   25
2    Eve   27

In [8]:
import numpy as np 
np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr, columns = ["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [9]:
#csv data
df = pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [10]:
#Methods 
print(df.head()) #starting 5 rows
print(df.describe())
print(df.sample())
print(df.tail(2))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000
   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000
   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [11]:
#AQI Data set 
df = pd.read_csv("globalAirQuality.csv")
df.head()
df.tail()
df.max()
df.min()

timestamp      2025-11-04 18:25:17.554219
country                                AE
city                             Auckland
latitude                          -37.814
longitude                        -123.121
pm25                                0.025
pm10                                0.061
no2                                 0.013
so2                                 0.003
o3                                  0.114
co                                    0.0
aqi                                    16
temperature                           5.0
humidity                           25.002
wind_speed                            0.5
dtype: object

In [12]:
#selecting the data 
df["city"]
df[["city","aqi"]]

df.loc[1]
df.loc[0:2]  #satrt index : end index (inclusive)

df.iloc[2]
df.iloc[0:2] # end index exclusive

df.iloc[0:2 , 2]
df.loc[0:2 , ["city","aqi","latitude","longitude"]]

       city  aqi  latitude  longitude
0  New York  108    40.713    -74.006
1  New York   90    40.713    -74.006
2  New York   84    40.713    -74.006

In [13]:
#Filtering of data
df[df["aqi"] > 100]
df[(df["aqi"] > 100)&(df["temperature"] > 30) ]
df[df["aqi"] > 100][["city","aqi"]]

           city  aqi
0      New York  108
3      New York  158
6      New York  155
7      New York  115
8      New York  121
...         ...  ...
17991    Zurich  104
17993    Zurich  153
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122

[9721 rows x 2 columns]

In [18]:
#Query
aqi_val =100
df.query("aqi >100 & temperature > 30")
df.query("aqi >@aqi_val & temperature > 30")
aqi_data = df.query("aqi >@aqi_val & temperature > 30").copy()